### ISSUE TITLE
Should dependencies.rosinstall use SSH or HTTPS?

### ISSUE THREAD

**Issue by rdube** [ethz-asl/segmatch#6]
@HannesSommer wstool update was failing for @CesarCadena for the dependencies specified with SSH as he had no SSH key setup on his virtual machine. Should we move all dependencies to use HTTPS or maybe have two dependencies scripts?

Also some dependencies url for the https are ending by .git and other don't. Should we normalize and put .git everywhere? 

Thanks! :)

**Comment by HannesSommer** [comment]
Yes, I would suggest `https` for all public repositories. That is the protocol (of the two) that allows fully anonymous cloning --- iff the repo is public. So for a all-public library (including its deps) that should be possible.

Yes, I would also normalize to with the `.git` extension. Seem cleaner to me because it goes in line with the git rule concerning the extension : with `.git` is a bare repo and without it is not. And these URLs point to bare repos.
Whether it is actually possible to clone with or without this extension most likely depends in practice on the hosting organization. But for github and bitbucket it seems to be fine.

**Comment by rdube** [comment]
Great thanks! Applied your suggestions in  #7.

**Comment by rdube** [comment]
First segmatch issue resolved! :-)
