### ISSUE TITLE
Random forest training code is not included?

### ISSUE THREAD

**Issue by wrockroll** [ethz-asl/segmatch#60]
Based on my current knowledge, the random forest training is given in [http://robotics.ethz.ch/segmatch/demonstration_files/kitti/] . Could you add random forest training code and dataset to guide how to train the classifier? Thank you!

**Comment by Durant35** [comment]
@wrockroll Could you make a comment on how to train the random forest as an example? It seems that some parameters are lost in yaml configure file. Thanks

**Comment by rdube** [comment]
@wrockroll for your information we will update segmatch soon and will not be supporting random forests anymore. The issue is that it can be too expensive to use when doing localization versus k-NN retrieval. With the upcoming version we do localization at 10Hz on velodyne data. See our RA-L paper on this strategy here: [incremental localization](http://www.gilitschenski.org/igor/publication/201801-ral-incremental_segmatch/)

Concerning the training we will be including a new descriptor shortly. You might want to have a look. Hope that helps!
